server:
  port: 8761

spring:
  application:
    name: DummyDiscovery
  main:
    banner-mode: "off"

eureka:
  instance:
    hostname: dummy_discovery  # 使用服务名称作为主机名
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/